In [9]:
import numpy as np

### About Numpy Array

- It consist of homogeneous data type
- It is faster than pythonlist because constructed using c++ and python lists are implemented using python
- It is better i memory utilization

In [10]:
# Creatig an array
array1 = np.array([1,2,3,4,5,6,7])
# 2D array 
array2D = np.array([[1,2,3,4],[5,6,7,8]])
print(array2D)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
# Creating multidimensional array using functions
# np.arrange np.linspace
array3 = np.arange(2,15, 0.5)
array3

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5])

In [17]:
array4 = np.linspace(2,3,num=5)
array4

array([2.  , 2.25, 2.5 , 2.75, 3.  ])