In [2]:
import numpy as np

### About Numpy Array

- It consist of homogeneous data type
- It is faster than pythonlist because constructed using c++ and python lists are implemented using python
- It is better i memory utilization

In [3]:
# Creatig an array
array1 = np.array([1,2,3,4,5,6,7])
# 2D array 
array2D = np.array([[1,2,3,4],[5,6,7,8]])
print(array2D)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
# Creating multidimensional array using functions
# np.arrange np.linspace
array3 = np.arange(2,15, 0.5)
array3

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5])

In [5]:
array4 = np.linspace(2,3,num=5)
array4

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [6]:
# 2D array
array5 = np.eye(2,3)
array5
#Create a matrix with diagonal element as 1

array([[1., 0., 0.],
       [0., 1., 0.]])

In [7]:
np.zeros((2,1))
# It creates 2 rows ans 1 cokumns


array([[0.],
       [0.]])

In [8]:
np.empty([4,5])

array([[ 4.24399158e-314,  5.30498948e-313,  2.12199581e-311,
         2.12229223e-314,  9.88131292e-324],
       [ 4.24399158e-313,  4.24399158e-313,  2.12199579e-314,
         2.12199579e-314,  2.12199579e-314],
       [ 2.12199579e-314,  2.12199579e-314,  2.12199579e-314,
         1.35807731e-312,  0.00000000e+000],
       [ 1.63150358e-319, -7.72076677e-087,  3.81959242e-311,
         4.94065646e-324,  0.00000000e+000]])

### Basic Operations

In [9]:
# Trignometric functions
c = np.array([[2,3],[5,6]])
d = np.array([[8,9],[2,3]])
np.dot(c,d)

array([[22, 27],
       [52, 63]])

In [10]:
# Trignometry
deg1= np.array([0,15,30,60])
trig1 = np.deg2rad(deg1)

print("Sin : ",np.sin(trig1))
print("Cos : ",np.cos(trig1))

Sin :  [0.         0.25881905 0.5        0.8660254 ]
Cos :  [1.         0.96592583 0.8660254  0.5       ]


- You can get Log
- Perform bitwise operations np.Bitwise_and()/Bitwise_or()

In [11]:
array6 = np.array([1,2,3,4,5])
print(np.sum(array6)) #sum
print(np.mean(array6)) #mean
print(np.median(array6)) #median
print(np.std(array6)) #Standard deviation
print(np.var(array6)) #Variance
print(np.max(array6)) #Maximum
print(np.min(array6)) #Minimum

15
3.0
3.0
1.4142135623730951
2.0
5
1


In [12]:
print(np.sort(array6)[::-1]) #Decending order

[5 4 3 2 1]


#### Boolean Indexing

In [13]:
arr = np.array([1,3,5,1,3,1,6,1,8,1,1])
arr[arr != 1] -= 1
print(arr)

[1 2 4 1 2 1 5 1 7 1 1]


##### Slicing

In [14]:
c = np.array([1,2,3,4,5])
c[2:4:1]

array([3, 4])

#### Reshaping, Splitting & Stacking of Arrays

In [18]:
# Reshaping
a= np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
# Splitting
b, c = np.split(a, 2, axis=0)
print(b)
print(c)

[[1 2 3]]
[[4 5 6]]


In [23]:
# Stacking
a = np.array([1,2,4])
b = np.array([5,6,8])
c = np.vstack((a,b))
d = np.hstack((a,b))
print(c)
print(d)

[[1 2 4]
 [5 6 8]]
[1 2 4 5 6 8]


In [29]:
# Concate
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
c = np.concatenate((a,b), axis = 0)
print(c)
d = np.concatenate((a,b), axis=None)
print(d)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [32]:
# Tranpose
a = np.array([[1,2],
             [3,4]])
print(a.size)
print(a.ndim)

4
2


In [33]:
a.T

array([[1, 3],
       [2, 4]])

In [34]:
print(a.size)
print(a.ndim)

4
2


#### Broadcasting